module.exports = {
    'Abraham Moss': 'G',
    Altrincham: 'A',
    Anchorage: 'D',
    'Ashton Moss': 'E',
    'Ashton West': 'E',
    'Ashton-Under-Lyne': 'E',
    Audenshaw: 'E',
    Baguley: 'F',
    'Barlow Moor Road': 'F',
    Benchill: 'F',
    'Besses o\'th\'Barn': 'G',
    'Bowker Vale': 'G',
    Broadway: 'E',
    Brooklands: 'A',
    'Burton Road': 'C',
    Bury: 'G',
    'Cemetery Road': 'E',
    'Central Park': 'H',
    Chorlton: 'J',
    'Clayton Hall': 'E',
    Cornbrook: 'A',
    Crossacres: 'F',
    Crumpsall: 'G',
    'Dane Road': 'A',
    'Deansgate-Castlefield': 'P',
    Derker: 'H',
    'Didsbury Village': 'C',
    Droylsden: 'E',
    'East Didsbury': 'C',
    Eccles: 'E',
    'Edge Lane': 'E',
    'Etihad Campus': 'G',
    'Exchange Quay': 'D',
    'Exchange Square': 'I',
    Failsworth: 'H',
    Firswood: 'J',
    Freehold: 'H',
    Martinscroft: 'F',
    'Old Trafford': 'A',
    Radcliffe: 'G',
    'Salford Quays': 'D',
    Stretford: 'A',
    'Trafford Bar': 'A',
    'Kingsway Business Park': 'I',
    Langworthy: 'E',
    'Navigation Road': 'A',
    'Harbour City': 'D',
    'Heaton Park': 'A',
    Hollinwood: 'H',
    'Holt Town': 'G',
    'Market Street': 'P',
    MediaCityUK: 'D',
    'Oldham King Street': 'H',
    Ladywell: 'E',
    'Manchester Airport': 'F',
    Milnrow: 'I',
    Monsall: 'H',
    'Moor Road': 'F',
    'New Islington': 'P',
    Newbold: 'I',
    Newhey: 'I',
    'Newton Heath and Moston': 'H',
    'Northern Moor': 'F',
    'Oldham Central': 'H',
    'Oldham Mumps': 'H',
    'Peel Hall': 'F',
    'Piccadilly Gardens': 'P',
    Piccadilly: 'P',
    Pomona: 'D',
    Prestwich: 'G',
    'Queens Road': 'G',
    'St Peters Square': 'P',
    'Robinswood Road': 'F',
    'Rochdale Railway station': 'I',
    'Rochdale Town Centre': 'I',
    Roundthorn: 'F',
    Sale: 'A',
    'Sale Water Park': 'F',
    Shadowmoss: 'F',
    'Shaw and Crompton': 'H',
    Shudehill: 'P',
    'South Chadderton': 'H',
    'St Werburghs Road': 'F',
    Timperley: 'A',
    Velopark: 'E',
    Victoria: 'P',
    Weaste: 'E',
    'West Didsbury': 'H',
    Westwood: 'H',
    Whitefield: 'G',
    Withington: 'H',
    'Wythenshawe Park': 'F',
    'Wythenshawe Town Centre': 'F'
};
